---
- name: Deploy my-simple-app (Docker already installed)
  hosts: all
  become: yes
  vars:
    app_name: my-simple-app
    app_image: 456501836709.dkr.ecr.eu-north-1.amazonaws.com/my-simple-app:latest
    app_ports:
      - "80:80"

  tasks:

    - name: Ensure Docker service is running
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Pull the latest image
      community.docker.docker_image:
        name: "{{ app_image }}"
        source: pull

    - name: Remove old container if exists
      community.docker.docker_container:
        name: "{{ app_name }}"
        state: absent

    - name: Start new container
      community.docker.docker_container:
        name: "{{ app_name }}"
        image: "{{ app_image }}"
        state: started
        restart_policy: always
        published_ports: "{{ app_ports }}"
