---
- name: Deploy my-simple-app safely
  hosts: web
  gather_facts: no
  become: yes
  vars:
    ecr_region: eu-north-1
    ecr_repo: 456501836709.dkr.ecr.eu-north-1.amazonaws.com/my-simple-app
    container_name: my-simple-app
    container_port: 80

  tasks:

    - name: Install Docker and dependencies (raw)
      ansible.builtin.raw: |
        sudo yum install -y docker yum-utils device-mapper-persistent-data lvm2
        sudo systemctl enable docker
        sudo systemctl start docker

    - name: Install Python Docker module (pip)
      ansible.builtin.pip:
        name: docker
        state: present

    - name: Login to AWS ECR
      ansible.builtin.shell: |
        aws ecr get-login-password --region {{ ecr_region }} | docker login --username AWS --password-stdin {{ ecr_repo }}
      environment:
        AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        AWS_DEFAULT_REGION: "{{ ecr_region }}"

    - name: Pull my-simple-app image from ECR
      community.docker.docker_image:
        name: "{{ ecr_repo }}:latest"
        source: pull

    - name: Remove old container if exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent

    - name: Run my-simple-app container
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ ecr_repo }}:latest"
        state: started
        restart_policy: always
        published_ports:
          - "{{ container_port }}:80"
