---
- name: Deploy my-simple-app (Docker already installed)
  hosts: ec2
  gather_facts: no   # Disable fact gathering
  vars:
    ecr_repo: "{{ ecr_repo }}"
    image_tag: "latest"
    commit_sha: "{{ commit_sha }}"
    container_name: "my-simple-app"
    exposed_port: 80
    container_port: 8090

  tasks:
    - name: Cleanup old container
      ansible.builtin.shell: |
        docker rm -f {{ container_name }} || true

    - name: Pull latest Docker image
      ansible.builtin.shell: |
        docker pull {{ ecr_repo }}:{{ image_tag }}
        docker pull {{ ecr_repo }}:{{ commit_sha }}

    - name: Run new container
      ansible.builtin.shell: |
        docker run -d -p {{ exposed_port }}:{{ container_port }} --name {{ container_name }} {{ ecr_repo }}:{{ image_tag }}

    - name: Get public IP
      ansible.builtin.shell: "curl -s http://169.254.169.254/latest/meta-data/public-ipv4"
      register: public_ip

    - name: Show live URL
      ansible.builtin.debug:
        msg: "✅ Your app is live at: http://{{ public_ip.stdout }}/"
